export enum BusinessType {
  WORKSHOP = "WORKSHOP",
  AUTO_CENTER = "AUTO_CENTER",
  AUTO_GLASS = "AUTO_GLASS",
  WINDOW_TINT = "WINDOW_TINT",
  LIGHTING = "LIGHTING",
  BATTERY = "BATTERY",
  TIRES_WHEELS = "TIRES_WHEELS",
  AUTO_ELECTRICAL = "AUTO_ELECTRICAL",
  AIR_CONDITIONING = "AIR_CONDITIONING",
  ACCESSORIES = "ACCESSORIES",
  DETAILING = "DETAILING",
  BODYWORK_PAINT = "BODYWORK_PAINT",
  OTHER = "OTHER",
}

export enum CatalogItemKind {
  PRODUCT = "PRODUCT",
  SERVICE = "SERVICE",
  PRODUCT_AND_SERVICE = "PRODUCT_AND_SERVICE",
}

export enum Channel {
  WEB = "WEB",
  WHATSAPP = "WHATSAPP",
  VOICE = "VOICE",
  INTERNAL = "INTERNAL",
  UNKNOWN = "UNKNOWN",
}

export enum ConversationStatus {
  ACTIVE = "ACTIVE",
  WAITING_CUSTOMER = "WAITING_CUSTOMER",
  WAITING_HUMAN = "WAITING_HUMAN",
  CLOSED = "CLOSED",
}

export enum CommercialOutcome {
  CONTACT_ONLY = "CONTACT_ONLY",
  LEAD = "LEAD",
  OPPORTUNITY = "OPPORTUNITY",
  QUOTE_REQUESTED = "QUOTE_REQUESTED",
  APPOINTMENT_REQUESTED = "APPOINTMENT_REQUESTED",
  APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED",
  HUMAN_HANDOFF = "HUMAN_HANDOFF",
  RESOLVED = "RESOLVED",
  IRRELEVANT = "IRRELEVANT",
}

export enum CommercialEventType {
  CONVERSATION_STARTED = "CONVERSATION_STARTED",
  INTENT_IDENTIFIED = "INTENT_IDENTIFIED",
  ITEM_REQUESTED = "ITEM_REQUESTED",
  SYMPTOM_REPORTED = "SYMPTOM_REPORTED",
  QUOTE_REQUESTED = "QUOTE_REQUESTED",
  QUOTE_RESPONDED = "QUOTE_RESPONDED",
  QUOTE_PUBLISHED = "QUOTE_PUBLISHED",
  APPOINTMENT_REQUESTED = "APPOINTMENT_REQUESTED",
  APPOINTMENT_CONFIRMED = "APPOINTMENT_CONFIRMED",
  OPPORTUNITY_CONVERTED = "OPPORTUNITY_CONVERTED",
  OPPORTUNITY_LOST = "OPPORTUNITY_LOST",
  MERCHANDISING_OFFER_PRESENTED = "MERCHANDISING_OFFER_PRESENTED",
  MERCHANDISING_OFFER_ACCEPTED = "MERCHANDISING_OFFER_ACCEPTED",
}

export enum AssistantHealthEventType {
  LOW_CONFIDENCE = "LOW_CONFIDENCE",
  AI_FAILURE = "AI_FAILURE",
  INTEGRATION_FAILURE = "INTEGRATION_FAILURE",
  UNKNOWN_INFORMATION = "UNKNOWN_INFORMATION",
  PRICE_UNAVAILABLE = "PRICE_UNAVAILABLE",
  HUMAN_HANDOFF = "HUMAN_HANDOFF",
  QUOTE_PUBLISH_FAILURE = "QUOTE_PUBLISH_FAILURE",
}

export enum SenderType {
  CUSTOMER = "CUSTOMER",
  ASSISTANT = "ASSISTANT",
  HUMAN_AGENT = "HUMAN_AGENT",
  SYSTEM = "SYSTEM",
}

export enum Intent {
  GENERAL_INFORMATION = "GENERAL_INFORMATION",
  SERVICE_INQUIRY = "SERVICE_INQUIRY",
  QUOTE_REQUEST = "QUOTE_REQUEST",
  APPOINTMENT_REQUEST = "APPOINTMENT_REQUEST",
  APPOINTMENT_CHANGE = "APPOINTMENT_CHANGE",
  APPOINTMENT_CANCEL = "APPOINTMENT_CANCEL",
  VEHICLE_STATUS = "VEHICLE_STATUS",
  WARRANTY = "WARRANTY",
  COMPLAINT = "COMPLAINT",
  HUMAN_REQUEST = "HUMAN_REQUEST",
  SYMPTOM_REPORT = "SYMPTOM_REPORT",
  OTHER = "OTHER",
  UNKNOWN = "UNKNOWN",
}

export enum OpportunityStatus {
  OPEN = "OPEN",
  WAITING_CUSTOMER = "WAITING_CUSTOMER",
  WAITING_BUSINESS = "WAITING_BUSINESS",
  CONVERTED = "CONVERTED",
  LOST = "LOST",
  CLOSED = "CLOSED",
}

export enum QuoteRequestStatus {
  REQUESTED = "REQUESTED",
  WAITING_INFORMATION = "WAITING_INFORMATION",
  WAITING_BUSINESS = "WAITING_BUSINESS",
  RESPONDED = "RESPONDED",
  CANCELLED = "CANCELLED",
  CLOSED = "CLOSED",
}

export enum AppointmentStatus {
  REQUESTED = "REQUESTED",
  CHECKING_AVAILABILITY = "CHECKING_AVAILABILITY",
  CONFIRMED = "CONFIRMED",
  RESCHEDULE_REQUESTED = "RESCHEDULE_REQUESTED",
  CANCEL_REQUESTED = "CANCEL_REQUESTED",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
}

export enum HandoffReason {
  CUSTOMER_REQUEST = "CUSTOMER_REQUEST",
  DIAGNOSIS_REQUIRED = "DIAGNOSIS_REQUIRED",
  SAFETY_CONCERN = "SAFETY_CONCERN",
  PRICE_UNAVAILABLE = "PRICE_UNAVAILABLE",
  NEGOTIATION_REQUIRED = "NEGOTIATION_REQUIRED",
  WARRANTY_OR_COMPLAINT = "WARRANTY_OR_COMPLAINT",
  LOW_CONFIDENCE = "LOW_CONFIDENCE",
  CONFLICTING_INFORMATION = "CONFLICTING_INFORMATION",
  INTEGRATION_FAILURE = "INTEGRATION_FAILURE",
  AI_FAILURE = "AI_FAILURE",
  UNKNOWN_INFORMATION = "UNKNOWN_INFORMATION",
  OTHER = "OTHER",
}

export enum HandoffStatus {
  REQUESTED = "REQUESTED",
  QUEUED = "QUEUED",
  ACCEPTED = "ACCEPTED",
  RESOLVED = "RESOLVED",
  CANCELLED = "CANCELLED",
}

export enum BusinessFactType {
  BUSINESS_HOURS = "BUSINESS_HOURS",
  ADDRESS = "ADDRESS",
  CONTACT = "CONTACT",
  SERVICE = "SERVICE",
  PRICE = "PRICE",
  PRICE_RANGE = "PRICE_RANGE",
  POLICY = "POLICY",
  WARRANTY = "WARRANTY",
  DISCOUNT_POLICY = "DISCOUNT_POLICY",
  PAYMENT_METHOD = "PAYMENT_METHOD",
  OTHER = "OTHER",
}
