import type {
  Appointment, AssistantHealthEvent, AutomotiveBusiness, CommercialEvent, Conversation, Customer,
  HumanHandoff, Message, Opportunity, QuoteRequest, Vehicle,
} from "../../core/domain/entities.js";
import {
  AssistantHealthEventType, BusinessType, Channel, CommercialEventType, CommercialOutcome,
  AppointmentStatus, ConversationStatus, HandoffReason, HandoffStatus, Intent, OpportunityStatus, QuoteRequestStatus, SenderType,
} from "../../core/domain/enums.js";
import type {
  AppointmentRepository, AssistantHealthEventRepository, AutomotiveBusinessRepository, CommercialEventRepository,
  ConversationRepository, CustomerRepository, HumanHandoffRepository, MessageRepository, OpportunityRepository,
  QuoteRequestRepository, VehicleRepository,
} from "../../core/repositories.js";
import type { EvolutionGoConversationLink, EvolutionGoConversationLinkRepository } from "../../channels/whatsapp/evolution-go-conversation-link.js";
import type { EvolutionGoWebhookClaimResult, EvolutionGoWebhookReplayClaim, EvolutionGoWebhookReplayClaimKey, EvolutionGoWebhookReplayGuard } from "../../channels/whatsapp/evolution-go-webhook-replay-guard.js";
import { PostgresDatabase } from "./postgres-database.js";

type Row = Record<string, unknown>;
const v = (row: Row, key: string): string => String(row[key]);
const nullable = (row: Row, key: string): string | undefined => row[key] == null ? undefined : String(row[key]);
function enumOf<T extends string>(values: readonly T[], value: unknown): T {
  if (typeof value === "string" && values.includes(value as T)) return value as T;
  throw new Error("PostgreSQL row contains an invalid enum value");
}
function optEnum<T extends string>(values: readonly T[], row: Row, key: string): T | undefined {
  return row[key] == null ? undefined : enumOf(values, row[key]);
}
function enumField<K extends string, T extends string>(property: K, values: readonly T[], row: Row, column: string): Partial<Record<K, T>> {
  const value = optEnum(values, row, column);
  return value === undefined ? {} : { [property]: value } as Record<K, T>;
}

export class PostgresAutomotiveBusinessRepository implements AutomotiveBusinessRepository {
  constructor(private readonly db: PostgresDatabase) {}
  async findById(id: string): Promise<AutomotiveBusiness | null> {
    try { const { rows } = await this.db.query("SELECT * FROM automotive_businesses WHERE id=$1", [id]); return rows[0] ? this.map(rows[0]) : null; }
    catch { throw new Error("Failed to load AutomotiveBusiness"); }
  }
  async save(e: AutomotiveBusiness): Promise<void> {
    try { await this.db.query(`INSERT INTO automotive_businesses(id,name,legal_name,business_type,phone,email,address,timezone,active,created_at,updated_at)
      VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(id) DO UPDATE SET name=excluded.name,legal_name=excluded.legal_name,
      business_type=excluded.business_type,phone=excluded.phone,email=excluded.email,address=excluded.address,timezone=excluded.timezone,
      active=excluded.active,created_at=excluded.created_at,updated_at=excluded.updated_at`,
    [e.id,e.name,e.legalName??null,e.businessType,e.phone??null,e.email??null,e.address??null,e.timezone,e.active,e.createdAt,e.updatedAt]); }
    catch { throw new Error("Failed to save AutomotiveBusiness"); }
  }
  private map(r: Row): AutomotiveBusiness { return { id:v(r,"id"),name:v(r,"name"),...(nullable(r,"legal_name")?{legalName:v(r,"legal_name")}:{}),businessType:enumOf(Object.values(BusinessType),r.business_type),...(nullable(r,"phone")?{phone:v(r,"phone")}:{ }),...(nullable(r,"email")?{email:v(r,"email")}:{ }),...(nullable(r,"address")?{address:v(r,"address")}:{ }),timezone:v(r,"timezone"),active:r.active===true,createdAt:v(r,"created_at"),updatedAt:v(r,"updated_at")}; }
}

export class PostgresCustomerRepository implements CustomerRepository {
  constructor(private readonly db: PostgresDatabase) {}
  async findById(businessId:string,id:string):Promise<Customer|null>{try{const {rows}=await this.db.query("SELECT * FROM customers WHERE business_id=$1 AND id=$2",[businessId,id]);const r=rows[0];const preferred= r ? optEnum(Object.values(Channel),r,"preferred_contact_channel") : undefined;return r?{id:v(r,"id"),businessId:v(r,"business_id"),...(nullable(r,"name")?{name:v(r,"name")}:{ }),...(nullable(r,"primary_phone")?{primaryPhone:v(r,"primary_phone")}:{ }),...(nullable(r,"email")?{email:v(r,"email")}:{ }),...(preferred?{preferredContactChannel:preferred}:{}),createdAt:v(r,"created_at"),updatedAt:v(r,"updated_at")}:null;}catch{throw new Error("Failed to load Customer");}}
  async save(e:Customer):Promise<void>{try{await this.db.query(`INSERT INTO customers(id,business_id,name,primary_phone,email,preferred_contact_channel,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(business_id,id) DO UPDATE SET name=excluded.name,primary_phone=excluded.primary_phone,email=excluded.email,preferred_contact_channel=excluded.preferred_contact_channel,created_at=excluded.created_at,updated_at=excluded.updated_at`,[e.id,e.businessId,e.name??null,e.primaryPhone??null,e.email??null,e.preferredContactChannel??null,e.createdAt,e.updatedAt]);}catch{throw new Error("Failed to save Customer");}}
}

export class PostgresVehicleRepository implements VehicleRepository {
  constructor(private readonly db:PostgresDatabase){}
  async findById(businessId:string,id:string):Promise<Vehicle|null>{try{const {rows}=await this.db.query("SELECT * FROM vehicles WHERE business_id=$1 AND id=$2",[businessId,id]);const r=rows[0];return r?{id:v(r,"id"),businessId:v(r,"business_id"),...(nullable(r,"customer_id")?{customerId:v(r,"customer_id")}:{ }),...(nullable(r,"brand")?{brand:v(r,"brand")}:{ }),...(nullable(r,"model")?{model:v(r,"model")}:{ }),...(r.year!=null?{year:Number(r.year)}:{ }),...(nullable(r,"version")?{version:v(r,"version")}:{ }),...(nullable(r,"license_plate")?{licensePlate:v(r,"license_plate")}:{ }),...(r.mileage!=null?{mileage:Number(r.mileage)}:{ }),createdAt:v(r,"created_at"),updatedAt:v(r,"updated_at")}:null;}catch{throw new Error("Failed to load Vehicle");}}
  async save(e:Vehicle):Promise<void>{try{await this.db.query(`INSERT INTO vehicles(id,business_id,customer_id,brand,model,year,version,license_plate,mileage,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(business_id,id) DO UPDATE SET customer_id=excluded.customer_id,brand=excluded.brand,model=excluded.model,year=excluded.year,version=excluded.version,license_plate=excluded.license_plate,mileage=excluded.mileage,created_at=excluded.created_at,updated_at=excluded.updated_at`,[e.id,e.businessId,e.customerId??null,e.brand??null,e.model??null,e.year??null,e.version??null,e.licensePlate??null,e.mileage??null,e.createdAt,e.updatedAt]);}catch{throw new Error("Failed to save Vehicle");}}
}

export class PostgresConversationRepository implements ConversationRepository {
  constructor(private readonly db:PostgresDatabase){}
  async findById(businessId:string,id:string):Promise<Conversation|null>{try{const {rows}=await this.db.query("SELECT * FROM conversations WHERE business_id=$1 AND id=$2",[businessId,id]);const r=rows[0];if(!r)return null;const outcome=optEnum(Object.values(CommercialOutcome),r,"commercial_outcome");const intent=optEnum(Object.values(Intent),r,"current_intent");return{id:v(r,"id"),businessId:v(r,"business_id"),...(nullable(r,"customer_id")?{customerId:v(r,"customer_id")}:{ }),...(nullable(r,"vehicle_id")?{vehicleId:v(r,"vehicle_id")}:{ }),channel:enumOf(Object.values(Channel),r.channel),status:enumOf(Object.values(ConversationStatus),r.status),...(outcome?{commercialOutcome:outcome}:{}),...(intent?{currentIntent:intent}:{}),startedAt:v(r,"started_at"),lastMessageAt:v(r,"last_message_at"),...(nullable(r,"closed_at")?{closedAt:v(r,"closed_at")}:{ })};}catch{throw new Error("Failed to load Conversation");}}
  async save(e:Conversation):Promise<void>{try{await this.db.query(`INSERT INTO conversations(id,business_id,customer_id,vehicle_id,channel,status,commercial_outcome,current_intent,started_at,last_message_at,closed_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT(business_id,id) DO UPDATE SET customer_id=excluded.customer_id,vehicle_id=excluded.vehicle_id,channel=excluded.channel,status=excluded.status,commercial_outcome=excluded.commercial_outcome,current_intent=excluded.current_intent,started_at=excluded.started_at,last_message_at=excluded.last_message_at,closed_at=excluded.closed_at`,[e.id,e.businessId,e.customerId??null,e.vehicleId??null,e.channel,e.status,e.commercialOutcome??null,e.currentIntent??null,e.startedAt,e.lastMessageAt,e.closedAt??null]);}catch{throw new Error("Failed to save Conversation");}}
}

export class PostgresMessageRepository implements MessageRepository {
  constructor(private readonly db:PostgresDatabase){}
  async save(e:Message):Promise<void>{try{await this.db.query(`INSERT INTO messages(id,business_id,conversation_id,sender_type,channel,content,external_message_id,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(business_id,id) DO UPDATE SET conversation_id=excluded.conversation_id,sender_type=excluded.sender_type,channel=excluded.channel,content=excluded.content,external_message_id=excluded.external_message_id,created_at=excluded.created_at`,[e.id,e.businessId,e.conversationId,e.senderType,e.channel,e.content,e.externalMessageId??null,e.createdAt]);}catch{throw new Error("Failed to save Message");}}
  async listByConversation(businessId:string,conversationId:string):Promise<Message[]>{try{const {rows}=await this.db.query("SELECT * FROM messages WHERE business_id=$1 AND conversation_id=$2 ORDER BY created_at,id",[businessId,conversationId]);return rows.map(r=>({id:v(r,"id"),businessId:v(r,"business_id"),conversationId:v(r,"conversation_id"),senderType:enumOf(Object.values(SenderType),r.sender_type),channel:enumOf(Object.values(Channel),r.channel),content:v(r,"content"),...(nullable(r,"external_message_id")?{externalMessageId:v(r,"external_message_id")}:{ }),createdAt:v(r,"created_at")}));}catch{throw new Error("Failed to load Messages");}}
}

export class PostgresEvolutionGoConversationLinkRepository implements EvolutionGoConversationLinkRepository {
  constructor(private readonly db:PostgresDatabase){}
  runAtomically<T>(key:Pick<EvolutionGoConversationLink,"businessId"|"instanceName"|"senderJid">,operation:()=>Promise<T>):Promise<T>{return this.db.transaction(async(client)=>{
    await client.query("SELECT pg_advisory_xact_lock(hashtextextended($1, 0))",[evolutionGoConversationAdvisoryLockKey(key)]);
    return operation();
  });}
  async findBySender(businessId:string,instanceName:string,senderJid:string):Promise<EvolutionGoConversationLink|null>{try{const {rows}=await this.db.query("SELECT * FROM evolution_go_conversation_links WHERE business_id=$1 AND instance_name=$2 AND sender_jid=$3",[businessId,instanceName,senderJid]);const r=rows[0];return r?{businessId:v(r,"business_id"),instanceName:v(r,"instance_name"),senderJid:v(r,"sender_jid"),conversationId:v(r,"conversation_id"),createdAt:v(r,"created_at"),updatedAt:v(r,"updated_at")}:null;}catch{throw new Error("Failed to load Evolution Go conversation link");}}
  async save(e:EvolutionGoConversationLink):Promise<void>{try{await this.db.query(`INSERT INTO evolution_go_conversation_links(business_id,instance_name,sender_jid,conversation_id,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(business_id,instance_name,sender_jid) DO UPDATE SET conversation_id=excluded.conversation_id,updated_at=excluded.updated_at`,[e.businessId,e.instanceName,e.senderJid,e.conversationId,e.createdAt,e.updatedAt]);}catch{throw new Error("Failed to save Evolution Go conversation link");}}
}

export function evolutionGoConversationAdvisoryLockKey(
  key: Pick<EvolutionGoConversationLink,"businessId"|"instanceName"|"senderJid">,
): string {
  return JSON.stringify([key.businessId,key.instanceName,key.senderJid]);
}

export class PostgresEvolutionGoWebhookReplayGuard implements EvolutionGoWebhookReplayGuard {
  constructor(private readonly db:PostgresDatabase){}
  async claim(e:EvolutionGoWebhookReplayClaim):Promise<EvolutionGoWebhookClaimResult>{return this.db.transaction(async(client):Promise<EvolutionGoWebhookClaimResult>=>{const prior=await client.query("SELECT 1 FROM evolution_go_webhook_receipts WHERE business_id=$1 AND instance_name=$2 AND external_message_id=$3",[e.businessId,e.instanceName,e.externalMessageId]);if(prior.rowCount)return{status:"duplicate"};const inserted=await client.query("INSERT INTO evolution_go_webhook_claims(business_id,instance_name,external_message_id,claim_token,received_at,claimed_at,lease_until) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT DO NOTHING",[e.businessId,e.instanceName,e.externalMessageId,e.claimToken,e.receivedAt,e.claimedAt,e.leaseUntil]);if(inserted.rowCount)return{status:"claimed",claimToken:e.claimToken};const takeover=await client.query("UPDATE evolution_go_webhook_claims SET claim_token=$1,claimed_at=$2,lease_until=$3,received_at=$4 WHERE business_id=$5 AND instance_name=$6 AND external_message_id=$7 AND lease_until <= $2",[e.claimToken,e.claimedAt,e.leaseUntil,e.receivedAt,e.businessId,e.instanceName,e.externalMessageId]);if(takeover.rowCount)return{status:"claimed",claimToken:e.claimToken};const receipt=await client.query("SELECT 1 FROM evolution_go_webhook_receipts WHERE business_id=$1 AND instance_name=$2 AND external_message_id=$3",[e.businessId,e.instanceName,e.externalMessageId]);return receipt.rowCount?{status:"duplicate"}:{status:"in_progress"};});}
  async complete(e:EvolutionGoWebhookReplayClaimKey):Promise<boolean>{return this.db.transaction(async(client)=>{const claim=await client.query("SELECT received_at FROM evolution_go_webhook_claims WHERE business_id=$1 AND instance_name=$2 AND external_message_id=$3 AND claim_token=$4 FOR UPDATE",[e.businessId,e.instanceName,e.externalMessageId,e.claimToken]);if(!claim.rowCount)return false;const receipt=await client.query("INSERT INTO evolution_go_webhook_receipts(business_id,instance_name,external_message_id,received_at) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING",[e.businessId,e.instanceName,e.externalMessageId,claim.rows[0]!.received_at]);if(!receipt.rowCount)return false;const removed=await client.query("DELETE FROM evolution_go_webhook_claims WHERE business_id=$1 AND instance_name=$2 AND external_message_id=$3 AND claim_token=$4",[e.businessId,e.instanceName,e.externalMessageId,e.claimToken]);return removed.rowCount===1;});}
  async release(e:EvolutionGoWebhookReplayClaimKey):Promise<boolean>{const result=await this.db.query("DELETE FROM evolution_go_webhook_claims WHERE business_id=$1 AND instance_name=$2 AND external_message_id=$3 AND claim_token=$4",[e.businessId,e.instanceName,e.externalMessageId,e.claimToken]);return result.rowCount===1;}
}

// Remaining aggregate repositories are implemented in this module as ordinary SQL adapters.
export class PostgresCommercialEventRepository implements CommercialEventRepository {
  constructor(private readonly db:PostgresDatabase){}
  async append(e:CommercialEvent):Promise<void>{try{await this.db.query(`INSERT INTO commercial_events(id,business_id,event_type,conversation_id,customer_id,vehicle_id,opportunity_id,quote_request_id,channel,intent,commercial_outcome,business_type,country,state,city,region,category,requested_item,symptom,vehicle_brand,vehicle_model,vehicle_year,amount_cents,currency,occurred_at) VALUES(${Array.from({length:25},(_,i)=>`$${i+1}`).join(",")})`,[e.id,e.businessId,e.eventType,e.conversationId??null,e.customerId??null,e.vehicleId??null,e.opportunityId??null,e.quoteRequestId??null,e.channel??null,e.intent??null,e.commercialOutcome??null,e.businessType??null,e.country??null,e.state??null,e.city??null,e.region??null,e.category??null,e.requestedItem??null,e.symptom??null,e.vehicleBrand??null,e.vehicleModel??null,e.vehicleYear??null,e.amount?.amountCents??null,e.amount?.currency??null,e.occurredAt]);}catch{throw new Error("Failed to append CommercialEvent");}}
  async listByBusiness(id:string):Promise<CommercialEvent[]>{return this.list("business_id=$1",[id]);}
  async listByConversation(id:string,cid:string):Promise<CommercialEvent[]>{return this.list("business_id=$1 AND conversation_id=$2",[id,cid]);}
  private async list(where:string,args:unknown[]):Promise<CommercialEvent[]>{try{const {rows}=await this.db.query(`SELECT * FROM commercial_events WHERE ${where} ORDER BY occurred_at,id`,args);return rows.map(r=>({id:v(r,"id"),businessId:v(r,"business_id"),eventType:enumOf(Object.values(CommercialEventType),r.event_type),...(nullable(r,"conversation_id")?{conversationId:v(r,"conversation_id")}:{ }),...(nullable(r,"customer_id")?{customerId:v(r,"customer_id")}:{ }),...(nullable(r,"vehicle_id")?{vehicleId:v(r,"vehicle_id")}:{ }),...(nullable(r,"opportunity_id")?{opportunityId:v(r,"opportunity_id")}:{ }),...(nullable(r,"quote_request_id")?{quoteRequestId:v(r,"quote_request_id")}:{ }),...enumField("channel",Object.values(Channel),r,"channel"),...enumField("intent",Object.values(Intent),r,"intent"),...enumField("commercialOutcome",Object.values(CommercialOutcome),r,"commercial_outcome"),...enumField("businessType",Object.values(BusinessType),r,"business_type"),...(nullable(r,"country")?{country:v(r,"country")}:{ }),...(nullable(r,"state")?{state:v(r,"state")}:{ }),...(nullable(r,"city")?{city:v(r,"city")}:{ }),...(nullable(r,"region")?{region:v(r,"region")}:{ }),...(nullable(r,"category")?{category:v(r,"category")}:{ }),...(nullable(r,"requested_item")?{requestedItem:v(r,"requested_item")}:{ }),...(nullable(r,"symptom")?{symptom:v(r,"symptom")}:{ }),...(nullable(r,"vehicle_brand")?{vehicleBrand:v(r,"vehicle_brand")}:{ }),...(nullable(r,"vehicle_model")?{vehicleModel:v(r,"vehicle_model")}:{ }),...(r.vehicle_year!=null?{vehicleYear:Number(r.vehicle_year)}:{ }),...(r.amount_cents!=null?{amount:{amountCents:Number(r.amount_cents),currency:v(r,"currency") as "BRL"}}:{ }),occurredAt:v(r,"occurred_at")}));}catch{throw new Error("Failed to load CommercialEvents");}}
}

export class PostgresAssistantHealthEventRepository implements AssistantHealthEventRepository {
  constructor(private readonly db:PostgresDatabase){}
  async append(e:AssistantHealthEvent):Promise<void>{try{await this.db.query(`INSERT INTO assistant_health_events(id,business_id,event_type,conversation_id,opportunity_id,quote_request_id,channel,business_type,country,state,city,region,provider,model,reason,occurred_at) VALUES(${Array.from({length:16},(_,i)=>`$${i+1}`).join(",")})`,[e.id,e.businessId,e.eventType,e.conversationId??null,e.opportunityId??null,e.quoteRequestId??null,e.channel??null,e.businessType??null,e.country??null,e.state??null,e.city??null,e.region??null,e.provider??null,e.model??null,e.reason??null,e.occurredAt]);}catch{throw new Error("Failed to append AssistantHealthEvent");}}
  async listByBusiness(id:string):Promise<AssistantHealthEvent[]>{return this.list("business_id=$1",[id]);}
  async listByConversation(id:string,cid:string):Promise<AssistantHealthEvent[]>{return this.list("business_id=$1 AND conversation_id=$2",[id,cid]);}
  private async list(where:string,args:unknown[]):Promise<AssistantHealthEvent[]>{try{const {rows}=await this.db.query(`SELECT * FROM assistant_health_events WHERE ${where} ORDER BY occurred_at,id`,args);return rows.map(r=>({id:v(r,"id"),businessId:v(r,"business_id"),eventType:enumOf(Object.values(AssistantHealthEventType),r.event_type),...(nullable(r,"conversation_id")?{conversationId:v(r,"conversation_id")}:{ }),...(nullable(r,"opportunity_id")?{opportunityId:v(r,"opportunity_id")}:{ }),...(nullable(r,"quote_request_id")?{quoteRequestId:v(r,"quote_request_id")}:{ }),...enumField("channel",Object.values(Channel),r,"channel"),...enumField("businessType",Object.values(BusinessType),r,"business_type"),...(nullable(r,"country")?{country:v(r,"country")}:{ }),...(nullable(r,"state")?{state:v(r,"state")}:{ }),...(nullable(r,"city")?{city:v(r,"city")}:{ }),...(nullable(r,"region")?{region:v(r,"region")}:{ }),...(nullable(r,"provider")?{provider:v(r,"provider")}:{ }),...(nullable(r,"model")?{model:v(r,"model")}:{ }),...(nullable(r,"reason")?{reason:v(r,"reason")}:{ }),occurredAt:v(r,"occurred_at")}));}catch{throw new Error("Failed to load AssistantHealthEvents");}}
}

export class PostgresOpportunityRepository implements OpportunityRepository {
  constructor(private readonly db:PostgresDatabase){}
  async findById(b:string,id:string):Promise<Opportunity|null>{try{const {rows}=await this.db.query("SELECT * FROM opportunities WHERE business_id=$1 AND id=$2",[b,id]);return rows[0]?this.map(rows[0]):null;}catch{throw new Error("Failed to load Opportunity");}}
  async listByConversation(b:string,c:string):Promise<Opportunity[]>{try{const {rows}=await this.db.query("SELECT * FROM opportunities WHERE business_id=$1 AND conversation_id=$2 ORDER BY created_at,id",[b,c]);return rows.map(r=>this.map(r));}catch{throw new Error("Failed to load Opportunities");}}
  async save(e:Opportunity):Promise<void>{try{await this.db.query(`INSERT INTO opportunities(id,business_id,conversation_id,customer_id,vehicle_id,request_description,status,next_action,estimated_value_amount_cents,estimated_value_currency,realized_value_amount_cents,realized_value_currency,value_source,created_at,updated_at,closed_at) VALUES(${Array.from({length:16},(_,i)=>`$${i+1}`).join(",")}) ON CONFLICT(business_id,id) DO UPDATE SET conversation_id=excluded.conversation_id,customer_id=excluded.customer_id,vehicle_id=excluded.vehicle_id,request_description=excluded.request_description,status=excluded.status,next_action=excluded.next_action,estimated_value_amount_cents=excluded.estimated_value_amount_cents,estimated_value_currency=excluded.estimated_value_currency,realized_value_amount_cents=excluded.realized_value_amount_cents,realized_value_currency=excluded.realized_value_currency,value_source=excluded.value_source,created_at=excluded.created_at,updated_at=excluded.updated_at,closed_at=excluded.closed_at`,[e.id,e.businessId,e.conversationId,e.customerId??null,e.vehicleId??null,e.requestDescription??null,e.status,e.nextAction?JSON.stringify(e.nextAction):null,e.estimatedValue?.amountCents??null,e.estimatedValue?.currency??null,e.realizedValue?.amountCents??null,e.realizedValue?.currency??null,e.valueSource??null,e.createdAt,e.updatedAt,e.closedAt??null]);}catch{throw new Error("Failed to save Opportunity");}}
  private map(r:Row):Opportunity{const action=r.next_action==null?undefined:(typeof r.next_action==="string"?JSON.parse(r.next_action):r.next_action) as NonNullable<Opportunity["nextAction"]>;return{id:v(r,"id"),businessId:v(r,"business_id"),conversationId:v(r,"conversation_id"),...(nullable(r,"customer_id")?{customerId:v(r,"customer_id")}:{ }),...(nullable(r,"vehicle_id")?{vehicleId:v(r,"vehicle_id")}:{ }),...(nullable(r,"request_description")?{requestDescription:v(r,"request_description")}:{ }),status:enumOf(Object.values(OpportunityStatus),r.status),...(action===undefined?{}:{nextAction:action}),...(r.estimated_value_amount_cents!=null?{estimatedValue:{amountCents:Number(r.estimated_value_amount_cents),currency:v(r,"estimated_value_currency") as "BRL"}}:{ }),...(r.realized_value_amount_cents!=null?{realizedValue:{amountCents:Number(r.realized_value_amount_cents),currency:v(r,"realized_value_currency") as "BRL"}}:{ }),...(nullable(r,"value_source")?{valueSource:v(r,"value_source")}:{ }),createdAt:v(r,"created_at"),updatedAt:v(r,"updated_at"),...(nullable(r,"closed_at")?{closedAt:v(r,"closed_at")}:{ })};}
}

export class PostgresQuoteRequestRepository implements QuoteRequestRepository {
  constructor(private readonly db:PostgresDatabase){}
  async findById(b:string,id:string):Promise<QuoteRequest|null>{try{const {rows}=await this.db.query("SELECT * FROM quote_requests WHERE business_id=$1 AND id=$2",[b,id]);return rows[0]?this.map(rows[0]):null;}catch{throw new Error("Failed to load QuoteRequest");}}
  async listByBusiness(b:string):Promise<QuoteRequest[]>{try{const {rows}=await this.db.query("SELECT * FROM quote_requests WHERE business_id=$1 ORDER BY requested_at,id",[b]);return rows.map(r=>this.map(r));}catch{throw new Error("Failed to load QuoteRequests");}}
  async listByConversation(b:string,c:string):Promise<QuoteRequest[]>{try{const {rows}=await this.db.query("SELECT * FROM quote_requests WHERE business_id=$1 AND conversation_id=$2 ORDER BY created_at,id",[b,c]);return rows.map(r=>this.map(r));}catch{throw new Error("Failed to load QuoteRequests");}}
  async save(e:QuoteRequest):Promise<void>{try{await this.db.query(`INSERT INTO quote_requests(id,business_id,opportunity_id,conversation_id,customer_id,vehicle_id,request_description,symptom_description,status,requested_at,responded_at,authorized_price_amount_cents,authorized_price_currency,created_at,updated_at) VALUES(${Array.from({length:15},(_,i)=>`$${i+1}`).join(",")}) ON CONFLICT(business_id,id) DO UPDATE SET opportunity_id=excluded.opportunity_id,conversation_id=excluded.conversation_id,customer_id=excluded.customer_id,vehicle_id=excluded.vehicle_id,request_description=excluded.request_description,symptom_description=excluded.symptom_description,status=excluded.status,requested_at=excluded.requested_at,responded_at=excluded.responded_at,authorized_price_amount_cents=excluded.authorized_price_amount_cents,authorized_price_currency=excluded.authorized_price_currency,created_at=excluded.created_at,updated_at=excluded.updated_at`,[e.id,e.businessId,e.opportunityId,e.conversationId,e.customerId??null,e.vehicleId??null,e.requestDescription,e.symptomDescription??null,e.status,e.requestedAt,e.respondedAt??null,e.authorizedPrice?.amountCents??null,e.authorizedPrice?.currency??null,e.createdAt,e.updatedAt]);}catch{throw new Error("Failed to save QuoteRequest");}}
  private map(r:Row):QuoteRequest{return{id:v(r,"id"),businessId:v(r,"business_id"),opportunityId:v(r,"opportunity_id"),conversationId:v(r,"conversation_id"),...(nullable(r,"customer_id")?{customerId:v(r,"customer_id")}:{ }),...(nullable(r,"vehicle_id")?{vehicleId:v(r,"vehicle_id")}:{ }),requestDescription:v(r,"request_description"),...(nullable(r,"symptom_description")?{symptomDescription:v(r,"symptom_description")}:{ }),status:enumOf(Object.values(QuoteRequestStatus),r.status),requestedAt:v(r,"requested_at"),...(nullable(r,"responded_at")?{respondedAt:v(r,"responded_at")}:{ }),...(r.authorized_price_amount_cents!=null?{authorizedPrice:{amountCents:Number(r.authorized_price_amount_cents),currency:v(r,"authorized_price_currency") as "BRL"}}:{ }),createdAt:v(r,"created_at"),updatedAt:v(r,"updated_at")};}
}

export class PostgresAppointmentRepository implements AppointmentRepository {
  constructor(private readonly db:PostgresDatabase){}
  async findById(b:string,id:string):Promise<Appointment|null>{try{const {rows}=await this.db.query("SELECT * FROM appointments WHERE business_id=$1 AND id=$2",[b,id]);const r=rows[0];return r?{id:v(r,"id"),businessId:v(r,"business_id"),...(nullable(r,"opportunity_id")?{opportunityId:v(r,"opportunity_id")}:{ }),conversationId:v(r,"conversation_id"),...(nullable(r,"customer_id")?{customerId:v(r,"customer_id")}:{ }),...(nullable(r,"vehicle_id")?{vehicleId:v(r,"vehicle_id")}:{ }),...(nullable(r,"requested_date")?{requestedDate:v(r,"requested_date")}:{ }),...(nullable(r,"requested_time")?{requestedTime:v(r,"requested_time")}:{ }),...(nullable(r,"confirmed_start_at")?{confirmedStartAt:v(r,"confirmed_start_at")}:{ }),status:enumOf(Object.values(AppointmentStatus),r.status),...(nullable(r,"request_description")?{requestDescription:v(r,"request_description")}:{ }),...(nullable(r,"external_appointment_id")?{externalAppointmentId:v(r,"external_appointment_id")}:{ }),createdAt:v(r,"created_at"),updatedAt:v(r,"updated_at")}:null;}catch{throw new Error("Failed to load Appointment");}}
  async save(e:Appointment):Promise<void>{try{await this.db.query(`INSERT INTO appointments(id,business_id,opportunity_id,conversation_id,customer_id,vehicle_id,requested_date,requested_time,confirmed_start_at,status,request_description,external_appointment_id,created_at,updated_at) VALUES(${Array.from({length:14},(_,i)=>`$${i+1}`).join(",")}) ON CONFLICT(business_id,id) DO UPDATE SET opportunity_id=excluded.opportunity_id,conversation_id=excluded.conversation_id,customer_id=excluded.customer_id,vehicle_id=excluded.vehicle_id,requested_date=excluded.requested_date,requested_time=excluded.requested_time,confirmed_start_at=excluded.confirmed_start_at,status=excluded.status,request_description=excluded.request_description,external_appointment_id=excluded.external_appointment_id,created_at=excluded.created_at,updated_at=excluded.updated_at`,[e.id,e.businessId,e.opportunityId??null,e.conversationId,e.customerId??null,e.vehicleId??null,e.requestedDate??null,e.requestedTime??null,e.confirmedStartAt??null,e.status,e.requestDescription??null,e.externalAppointmentId??null,e.createdAt,e.updatedAt]);}catch{throw new Error("Failed to save Appointment");}}
}

export class PostgresHumanHandoffRepository implements HumanHandoffRepository {
  constructor(private readonly db:PostgresDatabase){}
  async findById(b:string,id:string):Promise<HumanHandoff|null>{try{const {rows}=await this.db.query("SELECT * FROM human_handoffs WHERE business_id=$1 AND id=$2",[b,id]);const r=rows[0];return r?{id:v(r,"id"),businessId:v(r,"business_id"),conversationId:v(r,"conversation_id"),...(nullable(r,"opportunity_id")?{opportunityId:v(r,"opportunity_id")}:{ }),reason:enumOf(Object.values(HandoffReason),r.reason),summary:v(r,"summary"),status:enumOf(Object.values(HandoffStatus),r.status),...(nullable(r,"assigned_to")?{assignedTo:v(r,"assigned_to")}:{ }),requestedAt:v(r,"requested_at"),...(nullable(r,"accepted_at")?{acceptedAt:v(r,"accepted_at")}:{ }),...(nullable(r,"resolved_at")?{resolvedAt:v(r,"resolved_at")}:{ }),createdAt:v(r,"created_at"),updatedAt:v(r,"updated_at")}:null;}catch{throw new Error("Failed to load HumanHandoff");}}
  async save(e:HumanHandoff):Promise<void>{try{await this.db.query(`INSERT INTO human_handoffs(id,business_id,conversation_id,opportunity_id,reason,summary,status,assigned_to,requested_at,accepted_at,resolved_at,created_at,updated_at) VALUES(${Array.from({length:13},(_,i)=>`$${i+1}`).join(",")}) ON CONFLICT(business_id,id) DO UPDATE SET conversation_id=excluded.conversation_id,opportunity_id=excluded.opportunity_id,reason=excluded.reason,summary=excluded.summary,status=excluded.status,assigned_to=excluded.assigned_to,requested_at=excluded.requested_at,accepted_at=excluded.accepted_at,resolved_at=excluded.resolved_at,created_at=excluded.created_at,updated_at=excluded.updated_at`,[e.id,e.businessId,e.conversationId,e.opportunityId??null,e.reason,e.summary,e.status,e.assignedTo??null,e.requestedAt,e.acceptedAt??null,e.resolvedAt??null,e.createdAt,e.updatedAt]);}catch{throw new Error("Failed to save HumanHandoff");}}
}
